### ISSUE TITLE
安装过程中报错

### ISSUE THREAD

**Issue by lanrenwo** [douban/code#14]
CentOS 6.4 (64位)
Python 2.6.6

```lbash
RuntimeError: maximum recursion depth exceeded
/usr/local/soft/code/venv/build/MySQL-python/distribute-0.6.28-py2.6.egg
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/usr/local/soft/code/venv/build/MySQL-python/setup.py", line 7, in <module>
    use_setuptools()
  File "distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /usr/local/soft/code/venv/build/MySQL-python
Storing debug log for failure in /root/.pip/pip.log
Start serveing!!!
./quick_start.sh: line 18: gunicorn: command not found

**Comment by jumping** [comment]
@liaofeng  你是什么环境下安装的？我的10.10.1 Yosemite 一直装不了，正在CentOS上试

**Comment by jumping** [comment]
报错
```
Start app...
2015-01-23 07:58:19 [13884] [INFO] Starting gunicorn 18.0
2015-01-23 07:58:19 [13884] [INFO] Listening at: http://127.0.0.1:8000 (13884)
2015-01-23 07:58:19 [13884] [INFO] Using worker: sync
2015-01-23 07:58:19 [13889] [INFO] Booting worker with pid: 13889
2015-01-23 07:58:19 [13889] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ec2-user/code/scripts/code/app.py", line 5, in <module>
    from web import app as web
  File "/home/ec2-user/code/scripts/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/home/ec2-user/code/scripts/code/vilya/views/__init__.py", line 8, in <module>
    from vilya.views.organizations import OrganizationUI
  File "/home/ec2-user/code/scripts/code/vilya/views/organizations/__init__.py", line 6, in <module>
    from vilya.models.organization import Organization
  File "/home/ec2-user/code/scripts/code/vilya/models/organization.py", line 5, in <module>
    from vilya.libs.store import OrzField, store, IntegrityError, OrzBase
  File "/home/ec2-user/code/scripts/code/vilya/libs/store.py", line 6, in <module>
    from douban.mc import mc_from_config, create_decorators
  File "/usr/lib/python2.7/site-packages/DoubanMC-0.0.1-py2.7.egg/douban/mc/__init__.py", line 9, in <module>
    import cmemcached
ImportError: No module named cmemcached
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ec2-user/code/scripts/code/app.py", line 5, in <module>
    from web import app as web
  File "/home/ec2-user/code/scripts/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/home/ec2-user/code/scripts/code/vilya/views/__init__.py", line 8, in <module>
    from vilya.views.organizations import OrganizationUI
  File "/home/ec2-user/code/scripts/code/vilya/views/organizations/__init__.py", line 6, in <module>
    from vilya.models.organization import Organization
  File "/home/ec2-user/code/scripts/code/vilya/models/organization.py", line 5, in <module>
    from vilya.libs.store import OrzField, store, IntegrityError, OrzBase
  File "/home/ec2-user/code/scripts/code/vilya/libs/store.py", line 6, in <module>
    from douban.mc import mc_from_config, create_decorators
  File "/usr/lib/python2.7/site-packages/DoubanMC-0.0.1-py2.7.egg/douban/mc/__init__.py", line 9, in <module>
    import cmemcached
ImportError: No module named cmemcached
2015-01-23 07:58:19 [13889] [INFO] Worker exiting (pid: 13889)
2015-01-23 07:58:19 [13890] [INFO] Booting worker with pid: 13890
2015-01-23 07:58:19 [13890] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ec2-user/code/scripts/code/app.py", line 5, in <module>
    from web import app as web
  File "/home/ec2-user/code/scripts/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/home/ec2-user/code/scripts/code/vilya/views/__init__.py", line 8, in <module>
    from vilya.views.organizations import OrganizationUI
  File "/home/ec2-user/code/scripts/code/vilya/views/organizations/__init__.py", line 6, in <module>
    from vilya.models.organization import Organization
  File "/home/ec2-user/code/scripts/code/vilya/models/organization.py", line 5, in <module>
    from vilya.libs.store import OrzField, store, IntegrityError, OrzBase
  File "/home/ec2-user/code/scripts/code/vilya/libs/store.py", line 6, in <module>
    from douban.mc import mc_from_config, create_decorators
  File "/usr/lib/python2.7/site-packages/DoubanMC-0.0.1-py2.7.egg/douban/mc/__init__.py", line 9, in <module>
    import cmemcached
ImportError: No module named cmemcached
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ec2-user/code/scripts/code/app.py", line 5, in <module>
    from web import app as web
  File "/home/ec2-user/code/scripts/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/home/ec2-user/code/scripts/code/vilya/views/__init__.py", line 8, in <module>
    from vilya.views.organizations import OrganizationUI
  File "/home/ec2-user/code/scripts/code/vilya/views/organizations/__init__.py", line 6, in <module>
    from vilya.models.organization import Organization
  File "/home/ec2-user/code/scripts/code/vilya/models/organization.py", line 5, in <module>
    from vilya.libs.store import OrzField, store, IntegrityError, OrzBase
  File "/home/ec2-user/code/scripts/code/vilya/libs/store.py", line 6, in <module>
    from douban.mc import mc_from_config, create_decorators
  File "/usr/lib/python2.7/site-packages/DoubanMC-0.0.1-py2.7.egg/douban/mc/__init__.py", line 9, in <module>
    import cmemcached
ImportError: No module named cmemcached
2015-01-23 07:58:19 [13890] [INFO] Worker exiting (pid: 13890)
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==18.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 71, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 143, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 298, in halt
    self.stop()
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 341, in stop
    self.reap_workers()
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 452, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by jumping** [comment]
重新编译python-libmemcached后，错误消失。

**Comment by jumping** [comment]
目前问题是：
ImportError: /usr/lib64/python2.7/site-packages/_pygit2.so: undefined symbol: libssh2_channel_free

**Comment by xtao** [comment]
@jumping 你的 pygit2 是如何安装的？

**Comment by jumping** [comment]
@xtao  
我是先git clone https://github.com/douban/pygit2 ，然后按照的。

**Comment by xtao** [comment]
@jumping 你的依赖不正确，应该按照README里面的方式安装，https://github.com/douban/code/blob/master/requirements.txt 这个文件里面有指定版本号。

**Comment by jumping** [comment]
我用pip install -r  requirements.txt
<https://github.com/douban/code/blob/master/requirements.txt> 后，出现如下错误

```
...
lve and .require separately.
Obtaining DoubanUtils from git+
https://github.com/douban/douban-utils.git@5ca697545da191dab3fbe308e6b6776d8da83bd5#egg=DoubanUtils
(from -r requirements.txt (line 11))
  Updating ./src/doubanutils clone (to
5ca697545da191dab3fbe308e6b6776d8da83bd5)
  Could not find a tag or branch
'5ca697545da191dab3fbe308e6b6776d8da83bd5', assuming commit.
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown
distribution option: 'install_package_data'
      warnings.warn(msg)
    /home/ec2-user/code/src/doubanutils/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
      KEYWORDS = ""
Obtaining DoubanSQLStore from git+
https://github.com/douban/douban-sqlstore.git@d7136b7cac1075f0b285e8c763af2e85124f8b76#egg=DoubanSQLStore
(from -r requirements.txt (line 12))
  Updating ./src/doubansqlstore clone (to
d7136b7cac1075f0b285e8c763af2e85124f8b76)
  Could not find a tag or branch
'd7136b7cac1075f0b285e8c763af2e85124f8b76', assuming commit.
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown
distribution option: 'install_package_data'
      warnings.warn(msg)
    /home/ec2-user/code/src/doubansqlstore/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
      KEYWORDS = "MySQL"
Obtaining DoubanMC from git+
https://github.com/douban/douban-mc.git@f594ab28af464f25a54263d1cc312e895e65b1f4#egg=DoubanMC
(from -r requirements.txt (line 13))
  Updating ./src/doubanmc clone (to
f594ab28af464f25a54263d1cc312e895e65b1f4)
  Could not find a tag or branch
'f594ab28af464f25a54263d1cc312e895e65b1f4', assuming commit.
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown
distribution option: 'install_package_data'
      warnings.warn(msg)
    /home/ec2-user/code/src/doubanmc/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
      KEYWORDS = ""
Obtaining ORZ from git+
https://github.com/douban/douban-orz.git@208b48177dc847ef2afdadfda302868c39797bdf#egg=ORZ
(from -r requirements.txt (line 14))
  Updating ./src/orz clone (to 208b48177dc847ef2afdadfda302868c39797bdf)
  Could not find a tag or branch
'208b48177dc847ef2afdadfda302868c39797bdf', assuming commit.
    /home/ec2-user/code/src/orz/setup.py:12: DeprecationWarning: Parameters
to load are deprecated.  Call .resolve and .require separately.
      CLASSIFIERS = []
Obtaining Quixote from git+
https://github.com/douban/douban-quixote.git@72fd1b6f1224519709df2c031afc4bd9dbe611e4#egg=Quixote
(from -r requirements.txt (line 15))
  Updating ./src/quixote clone (to 72fd1b6f1224519709df2c031afc4bd9dbe611e4)
  Could not find a tag or branch
'72fd1b6f1224519709df2c031afc4bd9dbe611e4', assuming commit.
    /home/ec2-user/code/src/quixote/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
Obtaining pygit2 from git+
https://github.com/douban/pygit2.git@c7b13237e9934b5620cf0c351ae7eaea7d14ffc3#egg=pygit2
(from -r requirements.txt (line 16))
  Updating ./src/pygit2 clone (to c7b13237e9934b5620cf0c351ae7eaea7d14ffc3)
  Could not find a tag or branch
'c7b13237e9934b5620cf0c351ae7eaea7d14ffc3', assuming commit.
    checkout libgit2 source
    build libgit2 embed
    /home/ec2-user/code/src/pygit2/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
      # version of this file into combinations with other programs,
Obtaining ellen from git+
https://github.com/douban/ellen.git@e092eddd933a4676c53f016d11782897807f873a#egg=ellen
(from -r requirements.txt (line 17))
  Cloning https://github.com/douban/ellen.git (to
e092eddd933a4676c53f016d11782897807f873a) to ./src/ellen
  Could not find a tag or branch
'e092eddd933a4676c53f016d11782897807f873a', assuming commit.
    /home/ec2-user/code/src/ellen/setup.py:12: DeprecationWarning:
Parameters to load are deprecated.  Call .resolve and .require separately.
      with open('README.md') as long_description_file:
Obtaining python-libmemcached from git+
https://github.com/douban/python-libmemcached.git@71fb66d473bbab82c2b6ddb410a386dd84417fa3#egg=python_libmemcached
(from -r requirements.txt (line 18))
  Cloning https://github.com/douban/python-libmemcached.git (to
71fb66d473bbab82c2b6ddb410a386dd84417fa3) to ./src/python-libmemcached
  Could not find a tag or branch
'71fb66d473bbab82c2b6ddb410a386dd84417fa3', assuming commit.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/home/ec2-user/code/src/python-libmemcached/setup.py", line 5,
in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/home/ec2-user/code/src/python-libmemcached/setup.py", line 5,
in <module>

        from Cython.Distutils import build_ext

    ImportError: No module named Cython.Distutils

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in
/home/ec2-user/code/src/python-libmemcached
```

Best Regards,
Jumping Qu


------
Failure will absolutely happen. Things will absolutely go wrong. The best
way to deal with failure is to expect it and have a contingency plan in
place.

**Comment by jumping** [comment]
在Ubuntu 14.04上部署正常。

**Comment by jumping** [comment]
![image](https://cloud.githubusercontent.com/assets/255390/5896568/c286d312-a572-11e4-9911-8c0eb306a935.png)

好素净的界面
