### ISSUE TITLE
启动报错提示 undefined symbol: git_oid_equal   与配置的问题

### ISSUE THREAD

**Issue by aqqwiyth** [douban/code#57]
(venv)[root@BJNET-APP-99 code]# gunicorn -w 2 -b 127.0.0.1:8800 app:app
2014-05-06 16:30:50 [25604] [INFO] Starting gunicorn 18.0
2014-05-06 16:30:50 [25604] [INFO] Listening at: http://127.0.0.1:8800 (25604)
2014-05-06 16:30:50 [25604] [INFO] Using worker: sync
2014-05-06 16:30:50 [25609] [INFO] Booting worker with pid: 25609
2014-05-06 16:30:50 [25610] [INFO] Booting worker with pid: 25610
2014-05-06 16:30:50 [25609] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/data/project/code/app.py", line 5, in <module>
    from web import app as web
  File "/data/project/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/data/project/code/vilya/views/__init__.py", line 9, in <module>
    from vilya.views.users import UserUI
  File "/data/project/code/vilya/views/users/__init__.py", line 6, in <module>
    from vilya.models.project import Project
  File "/data/project/code/vilya/models/project.py", line 9, in <module>
    from vilya.models.git.repo import ProjectRepo
  File "/data/project/code/vilya/models/git/repo.py", line 12, in <module>
    from ellen.repo import Jagare
  File "/data/project/code/venv/src/ellen/ellen/repo.py", line 6, in <module>
    from pygit2 import Repository
  File "/data/project/code/venv/src/pygit2/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /data/project/code/venv/src/pygit2/_pygit2.so: undefined symbol: git_oid_equal
Traceback (most recent call last):
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/data/project/code/app.py", line 5, in <module>
    from web import app as web
  File "/data/project/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/data/project/code/vilya/views/__init__.py", line 9, in <module>
    from vilya.views.users import UserUI
  File "/data/project/code/vilya/views/users/__init__.py", line 6, in <module>
    from vilya.models.project import Project
  File "/data/project/code/vilya/models/project.py", line 9, in <module>
    from vilya.models.git.repo import ProjectRepo
  File "/data/project/code/vilya/models/git/repo.py", line 12, in <module>
    from ellen.repo import Jagare
  File "/data/project/code/venv/src/ellen/ellen/repo.py", line 6, in <module>
    from pygit2 import Repository
  File "/data/project/code/venv/src/pygit2/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /data/project/code/venv/src/pygit2/_pygit2.so: undefined symbol: git_oid_equal
2014-05-06 16:30:50 [25609] [INFO] Worker exiting (pid: 25609)
2014-05-06 16:30:50 [25610] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/data/project/code/app.py", line 5, in <module>
    from web import app as web
  File "/data/project/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/data/project/code/vilya/views/__init__.py", line 9, in <module>
    from vilya.views.users import UserUI
  File "/data/project/code/vilya/views/users/__init__.py", line 6, in <module>
    from vilya.models.project import Project
  File "/data/project/code/vilya/models/project.py", line 9, in <module>
    from vilya.models.git.repo import ProjectRepo
  File "/data/project/code/vilya/models/git/repo.py", line 12, in <module>
    from ellen.repo import Jagare
  File "/data/project/code/venv/src/ellen/ellen/repo.py", line 6, in <module>
    from pygit2 import Repository
  File "/data/project/code/venv/src/pygit2/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /data/project/code/venv/src/pygit2/_pygit2.so: undefined symbol: git_oid_equal
Traceback (most recent call last):
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/data/project/code/app.py", line 5, in <module>
    from web import app as web
  File "/data/project/code/web.py", line 11, in <module>
    from vilya import views as controllers
  File "/data/project/code/vilya/views/__init__.py", line 9, in <module>
    from vilya.views.users import UserUI
  File "/data/project/code/vilya/views/users/__init__.py", line 6, in <module>
    from vilya.models.project import Project
  File "/data/project/code/vilya/models/project.py", line 9, in <module>
    from vilya.models.git.repo import ProjectRepo
  File "/data/project/code/vilya/models/git/repo.py", line 12, in <module>
    from ellen.repo import Jagare
  File "/data/project/code/venv/src/ellen/ellen/repo.py", line 6, in <module>
    from pygit2 import Repository
  File "/data/project/code/venv/src/pygit2/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /data/project/code/venv/src/pygit2/_pygit2.so: undefined symbol: git_oid_equal
2014-05-06 16:30:50 [25610] [INFO] Worker exiting (pid: 25610)
Traceback (most recent call last):
  File "/data/project/code/venv/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==18.0', 'console_scripts', 'gunicorn')()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 71, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 143, in run
    Arbiter(self).run()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 298, in halt
    self.stop()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 341, in stop
    self.reap_workers()
  File "/data/project/code/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 452, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

还有问一下：local_config.py 与config.py的关系是什么
gunicorn -w 2 -b 127.0.0.1:8000 app:app  启动会选择哪一个配置文件？

**Comment by dongweiming** [comment]
@aqqwiyth 欢迎再试.
