### ISSUE TITLE
安装了所有相关程序，还是报错啊，请明示怎么解决啊

### ISSUE THREAD

**Issue by alemic** [douban/code#62]
报错信息
[root@su code]# gunicorn -w 2 -b 0.0.0.0:8000 app:app
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.1.1', 'console_scripts', 'gunicorn')()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/arbiter.py", line 169, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/arbiter.py", line 542, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn-19.1.1-py2.7.egg/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by jumping** [comment]
安装还是有些难度的。

**Comment by dongweiming** [comment]
@alemic 现在可以使用vagrant启动一个ubuntu的测试环境了. 配置过程的历史记录都还在, 可以参考
