### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by hailinzeng** [douban/code#63]
启动后, 需要访问数据库的signup/expore/search页面报如下错误

2015-01-25 18:09:28 [17913] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hailin/code/app.py", line 19, in __call__
    return func(environ, start_response)
  File "/home/hailin/code/vilya/libs/gzipper.py", line 57, in __call__
    response.gzip_start_response)
  File "/home/hailin/code/src/quixote/quixote/qwip.py", line 32, in __call__
    output = self.publisher.process_request(request, env)
  File "/home/hailin/code/src/quixote/quixote/publish.py", line 551, in process_request
    output = self.finish_failed_request(request)
  File "/home/hailin/code/src/quixote/quixote/publish.py", line 545, in process_request
    output = self.try_publish(request, env.get('PATH_INFO', ''))
  File "/home/hailin/code/web.py", line 64, in try_publish
    output = Publisher.try_publish(self, request, path)
  File "/home/hailin/code/src/quixote/quixote/publish.py", line 464, in try_publish
    self.namespace_stack)
  File "/home/hailin/code/src/quixote/quixote/publish.py", line 731, in _traverse_url
    namespace_stack)
  File "/home/hailin/code/src/quixote/quixote/publish.py", line 834, in _get_component
    object = container._q_lookup(request, component)
  File "/home/hailin/code/vilya/views/__init__.py", line 47, in _q_lookup
    user = User.get_by_name(name)
  File "/home/hailin/code/vilya/models/user.py", line 30, in get_by_name
    rs = cls.gets_by(name=name)
  File "/home/hailin/code/src/orz/ORZ/klass_init.py", line 186, in gets_by
    return cls.objects.gets_by(*a, **kw)
  File "/home/hailin/code/src/orz/ORZ/cache_mgr.py", line 179, in gets_by
    return self.fetch(force_flush, kw, real_order_by, (start, limit))
  File "/home/hailin/code/src/orz/ORZ/cache_mgr.py", line 103, in fetch
    primary_field_vals = sql_executor.get_ids(conditions, _start_limit, order_keys)
  File "/home/hailin/code/src/orz/ORZ/sql_executor.py", line 64, in get_ids
    ids = map(itemgetter(0), self.sqlstore.execute(statement, tuple(chain(v1, v3))))
  File "/home/hailin/code/src/doubansqlstore/douban/sqlstore/__init__.py", line 719, in execute
    cursor = self.get_cursor(table=tables[0])
  File "/home/hailin/code/src/doubansqlstore/douban/sqlstore/__init__.py", line 666, in get_cursor
    cursor = farm.get_cursor()
  File "/home/hailin/code/src/doubansqlstore/douban/sqlstore/__init__.py", line 223, in get_cursor
    self.cursor = self.connect(**self.dbcnf)
  File "/home/hailin/code/src/doubansqlstore/douban/sqlstore/__init__.py", line 198, in connect
    return LuzCursor(cursor, self)
  File "/home/hailin/code/src/doubansqlstore/douban/sqlstore/__init__.py", line 912, in __init__
    self.cursor.execute(sql, self.cursor.connection.thread_id())
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: 'int' object is not iterable

**Comment by hanxi** [comment]
我的centos7也遇到了这个错误。都没人维护这个项目了。

**Comment by xtao** [comment]
2位，这个问题应该是 mysqldb 的版本问题，请看一下 requirements.txt 的里面的软件版本

**Comment by hanxi** [comment]
很定是版本问题的。我改了requirements.txt，把版本全部去掉了才安装成功。反正好多问题。。。如果有个稳定的版本就好了。
