### ISSUE TITLE
日拱一足

### ISSUE THREAD

**Issue by xtao** [douban/code#84]
[] Support vagrant provision (ansible)
[] Fix failed travis-ci

**Comment by xtao** [comment]
Vagrant box 相关问题记录:
- [ ] 默认用户说明，或者提供添加用户 shell cmd
- [ ] 注册用户

**Comment by xtao** [comment]
- [x]  Remove beansdb

**Comment by xtao** [comment]
- [] Remove SearchClientStub or Add es support.

**Comment by xtao** [comment]
- [x] Remove douvatar

**Comment by xtao** [comment]
- [ ] Migrate to Django

**Comment by xtao** [comment]
- [ ] Fix /favicon.ico

```
Traceback (most recent call last):
  File "/home/xtao/work/code/vilya/libs/gzipper.py", line 63, in __call__
    response.gzip_start_response)
  File "/home/xtao/work/code/venv/src/quixote/quixote/qwip.py", line 32, in __call__
    output = self.publisher.process_request(request, env)
  File "/home/xtao/work/code/venv/src/quixote/quixote/publish.py", line 545, in process_request
    output = self.try_publish(request, env.get('PATH_INFO', ''))
  File "/home/xtao/work/code/web.py", line 64, in try_publish
    output = SessionPublisher.try_publish(self, request, path)
  File "/home/xtao/work/code/venv/src/quixote/quixote/publish.py", line 464, in try_publish
    self.namespace_stack)
  File "/home/xtao/work/code/venv/src/quixote/quixote/publish.py", line 735, in _traverse_url
    namespace_stack)
  File "/home/xtao/work/code/venv/src/quixote/quixote/publish.py", line 847, in _get_component
    component))
TraversalError: object <module 'vilya.views' from '/home/xtao/work/code/vilya/views/__init__.pyc'> has no attribute 'favicon.ico'
```

**Comment by motecshine** [comment]
真棒

**Comment by xtao** [comment]
- [ ] Remove trello binding

**Comment by xtao** [comment]
- [x] Remove me.dapps

**Comment by xtao** [comment]
- [ ] Move celeryconfig to app settings

**Comment by xtao** [comment]
- [ ] Remove `code.intra.douban.com`

**Comment by xtao** [comment]
- [ ] Remove `p.dapps.douban.com`

**Comment by xtao** [comment]
- [ ] Remove `c.dapps.douban.com`

**Comment by xtao** [comment]
- [ ] Remove DIY oauth

**Comment by xtao** [comment]
- [ ] Add codelive back

**Comment by xtao** [comment]
- [ ] Issue 页面的 emoji 单个文件过多，导致页面响应慢(没有设置浏览器缓存)
