### ISSUE TITLE
MySQL数据库连接信息是在哪设置的？

### ISSUE THREAD

**Issue by ist0ne** [douban/code#86]
访问时报如下错误，好像默认使用root，无密码登陆

Traceback (most recent call last):
  File "/data/code/venv/src/quixote/quixote/publish.py", line 545, in process_request
    output = self.try_publish(request, env.get('PATH_INFO', ''))
  File "/data/code/web.py", line 56, in try_publish
    output = SessionPublisher.try_publish(self, request, path)
  File "/data/code/venv/src/quixote/quixote/publish.py", line 456, in try_publish
    self.start_request(request)
  File "/data/code/web.py", line 51, in start_request
    request.user = User.get_current_user()
  File "/data/code/vilya/models/user.py", line 120, in get_current_user
    user = get_current_user()
  File "/data/code/vilya/models/user.py", line 48, in get_current_user
    user = CodeUser.get(id=id)
  File "/data/code/vilya/libs/model.py", line 86, in get
    ret = cls.objects.gets_by(**kwargs)
  File "/data/code/venv/src/orz/ORZ/cache_mgr.py", line 179, in gets_by
    return self.fetch(force_flush, kw, real_order_by, (start, limit))
  File "/data/code/venv/src/orz/ORZ/cache_mgr.py", line 103, in fetch
    primary_field_vals = sql_executor.get_ids(conditions, _start_limit, order_keys)
  File "/data/code/venv/src/orz/ORZ/sql_executor.py", line 64, in get_ids
    ids = map(itemgetter(0), self.sqlstore.execute(statement, tuple(chain(v1, v3))))
  File "/data/code/venv/src/doubansqlstore/douban/sqlstore/__init__.py", line 719, in execute
    cursor = self.get_cursor(table=tables[0])
  File "/data/code/venv/src/doubansqlstore/douban/sqlstore/__init__.py", line 666, in get_cursor
    cursor = farm.get_cursor()
  File "/data/code/venv/src/doubansqlstore/douban/sqlstore/__init__.py", line 223, in get_cursor
    self.cursor = self.connect(**self.dbcnf)
  File "/data/code/venv/src/doubansqlstore/douban/sqlstore/__init__.py", line 184, in connect
    conn = MySQLdb.connect(**conn_params)
  File "/data/code/venv/src/mysql-python/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/data/code/venv/src/mysql-python/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by dongweiming** [comment]
@ist0ne CODE的配置都在 [vilya/config.py](https://github.com/douban/code/blob/master/vilya/config.py) 里面, 但是你可以在项目根目录(或者你启动时候的目录下)创建一个local_config.py文件, 重载这个数据库配置. 或者使用CODE提供的模板:

```python
cp vilya/local_config.py.tmpl vilya/local_config.py
```

比如修改数据库, 可以加上这段(只描述了格式, 你可以按你的实际环境修改)

```bash
MYSQL_STORE = {
    "farms": {
        "code_farm": {
            "master": "host:port:database_name:username:password",
            "tables": ["*"],
        }
    }
}
```

感谢提醒, 之后我会把这部分内容加进来.
